[project]
name = "create-litestar"
version = "0.1.3"
description = "Easy way to start a Litestar project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "copier>=9.10.3",
    "questionary>=2.1.1",
    "rich>=14.1.0",
    "ruff>=0.14.5",
]

[project.urls]
Discord = "https://discord.gg/litestar"
Funding = "https://github.com/sponsors/litestar-org"
Homepage = "https://github.com/Kumzy/create-litestar"
Issue = "https://github.com/Kumzy/create-litestar/issues/"
Source = "https://github.com/Kumzy/create-litestar"

[project.scripts]
create-litestar = "create_litestar.__main__:main"

[tool.ruff]
extend-exclude = ["src/templates/basic"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
test = [
    "pytest>=8.3.3",
]
lint = [
    "mypy>=1.12.0",
    "pre-commit>=3.5.0",
    "pyright>=1.1.385",
    "ruff>=0.6.8",
    "slotscheck>=0.16.5",
]
dev = [
    "structlog>=24.4.0",
]
